apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rekrutteringsbistand-stilling-kafkabro
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: rekrutteringsbistand-stilling-kafkabro
      rules:
        - alert: rekrutteringsbistand-stilling-kafkabro
          expr: kube_deployment_status_replicas_available{deployment="rekrutteringsbistand-stilling-kafkabro"} == 0
          for: 5m
          annotations:
            summary: Applikasjonen er nede
            action: "https://logs.adeo.no/app/r/s/VDMbI"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-stilling-kafkabro
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-stilling-kafkabro", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Applikasjonen har logget en error
            action: "https://logs.adeo.no/app/r/s/VDMbI"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-stilling-kafkabro
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-stilling-kafkabro", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/VDMbI"
          labels:
            namespace: toi
            severity: warning
