apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-kafkabro
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: ghcr.io/nais/aivia:latest
  liveness:
    path: "/internal/isalive"
  readiness:
    path: "/internal/isready"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  envFrom:
    - secret: rekrutteringsbistand-stilling-kafkabro-todo
  env:
    - name: AIVIA_SOURCE
      value: aiven
  filesFrom:
    - configmap: rekrutteringsbistand-stilling-kafkabro-topic-mapping
  kafka:
    pool: nav-dev