apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-kafkabro
  namespace: toi
  labels:
    team: toi
spec:
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/aivia:latest
  liveness:
    path: "/internal/isalive"
    initialDelay: 30
  readiness:
    path: "/internal/isready"
    initialDelay: 30
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: AIVIA_SOURCE
      value: aiven
    - name: NAIS_CLIENT_ID
      value: kafka-stilling-1 #Vi inkrementerer denne verdien når vi vil lese alt på topic fra starten av (nullstille offset)
    - name: LOG_FORMAT
      value: logstash
  filesFrom:
    - configmap: aivia-topic-mapping
  kafka:
    pool: {{kafka_pool}}
