name: "Deploy aivia"
on: [ push ]

jobs:
  deploy-to-dev:
    name: Deploy to dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alerts'
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VARS: nais-vars-dev.yaml
          RESOURCE: configmap.yaml,nais.yaml,topics/dev_rekrutteringsbistand-stilling.yaml

  deploy-to-prod:
    name: Deploy to prod
    needs: deploy-to-dev
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          VARS: nais-vars-prod.yaml
          RESOURCE: configmap.yaml,nais.yaml,topics/prod_rekrutteringsbistand-stilling.yaml,alerts.yaml
